name: Publish

on: [push]

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: ${{ contains(github.event.head_commit.message, '[PUBLISH]') }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pie
            asset_name: pie-linux-amd64
          - os: windows-latest
            artifact_name: pie.exe
            asset_name: pie-windows-amd64
          - os: macos-latest
            artifact_name: pie
            asset_name: pie-macos-amd64

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}