name: Publish

on: [push]

jobs:
  publish:
    if: ${{ contains(github.event.head_commit.message, '[PUBLISH]') }}
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: pie
            asset_name: linux-pie
          - os: windows-latest
            artifact_name: pie.exe
            asset_name: windows-pie.exe
          - os: macos-latest
            artifact_name: pie
            asset_name: macos-pie

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
            toolchain: stable
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: Release
        overwrite: true
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}